version: 1.0.{build}

skip_commits:
  files:
    - 'README.md'
    - '.gitignore'
    - '.github/workflows/*'
    
image: Visual Studio 2022
configuration: Debug
platform: x64

install:
  - cd C:\Tools\vcpkg
  - vcpkg version
  - vcpkg install boost-filesystem:x64-windows-static boost-format:x64-windows-static \
        boost-type-index:x64-windows-static boost-functional:x64-windows-static
  - vcpkg integrate install
  - cd %APPVEYOR_BUILD_FOLDER%
  
build:
  parallel: true
  verbosity: minimal
  
after_build:
- cmd: C:\projects\cpp-primer-5th-edition\x64\Debug\CppPrimer5th.exe 3 4

cache:
- c:\tools\vcpkg\installed\