name: Windows CI

on:
  push:
    branches: [ master ]
    paths-ignore:
        - 'README.md'
        - 'appveyor.yml'
        - 'AutoTest.vbs'
        - '.gitignore'
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  msvc2022:
    # windows-latest means Windows 10. And automatically installs Visual Studio 2019
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    # Also see: https://github.com/microsoft/setup-msbuild/issues/77
    - name: Setup msbuild and Visual Studio
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: 17.10.6
 
    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg install boost-filesystem:x64-windows-static boost-format:x64-windows-static boost-type-index:x64-windows-static boost-functional:x64-windows-static
        .\vcpkg\vcpkg integrate install

    - name: Build solution
      run: msbuild -t:rebuild /p:Configuration=Debug /p:Platform=x64 CppPrimer5th.sln

    - name: Run tests
      shell: cmd
      run: .\x64\Debug\CppPrimer5th.exe 3 4
    
