name: Windows CI

on:
  push:
    branches: [ master ]
    paths-ignore:
        - 'README.md'
        - 'appveyor.yml'
        - 'AutoTest.vbs'
        - '.gitignore'
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  msvc2022:
    # windows-latest means Windows 10. And automatically installs Visual Studio 2019
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    # Also see: https://github.com/microsoft/setup-msbuild/issues/77
    - name: Setup msbuild and Visual Studio
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: 17.10.5
 
    # https://github.com/marketplace/actions/build-boost
    - name: Install boost
      uses: egor-tensin/build-boost@v1
      id: install-boost
      with:
        version: 1.85.0
        libraries: system
        configuration: Debug
        platform: x64
        static: 1
        toolset: msvc143

    # 上一步编译的boost静态库没有版本后缀，会导致后续找不到链接库
    - name: Rename libboost
      shell: cmd
      run: for %%f in (${{ steps.install-boost.outputs.librarydir }}\libboost_*.lib) do ren "%%f" "%%~nf-vc143-mt-gd-x64-1_85.lib"

    - name: Build solution
      run: msbuild -t:rebuild /p:Configuration=Debug /p:Platform=x64 CppPrimer5th.sln
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.root }}
        BOOST_LIB: ${{ steps.install-boost.outputs.librarydir }}

    - name: Run tests
      shell: cmd
      run: |
          chcp 65001 #解决中文显示乱码
          .\x64\Debug\CppPrimer5th.exe 3 4
    
